{% set name = "sxs" %}
{% set version = "2024.0.44" %}
{% set sha256 = "a09d4408d10bde2f6612d9faca671dadb82bffa9e334e0632e72707e99509277" %}
{% set python_min = "3.10" %}

# See https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python for the reason we
# *can* set `python_min` here and https://github.com/conda-forge/cfep/blob/main/cfep-25.md
# for what `python_min` actually means.  I have to do this because conda-forge still supports
# python 3.9, but sxs only supports >=3.10.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    # See conda_build_config.yaml for list of pythons to build with
    - python {{ python_min }}
    - pip >=20.0.2
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - numba
    - h5py
    - requests
    - tqdm
    - pytz
    - pandas
    - inflection
    - requests
    - urllib3
    - quaternionic >=1.0
    - spherical >=1.0
    - pyjuliacall >=0.9.20

test:
  requires:
    - python {{ python_min }}
  imports:
    - sxs

about:
  home: https://github.com/sxs-collaboration/sxs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of python code used by the SXS collaboration
  description: |
    This package provides a number of utilities for use by the SXS collaboration, and others who use our data.
    For example, the `metadata` subpackage provides functions for reading and analyzing the metadata files
    provided with SXS simulations for describing the physics they represent.  Another important subpackage is
    `zenodo`, which provides handy functions for interacting with zenodo.org in general, and in particular our
    collection of simulation data on that site.
  dev_url: https://github.com/sxs-collaboration/sxs

extra:
  recipe-maintainers:
    - moble
