{% set name = "sxs" %}
{% set version = "2021.0.5" %}
{% set sha256 = "6ba3b02e0b83225b3ac310156f77c37c84f6214ad354df8b276e66cda91d1229" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv  # [not win]
  script: del /f pyproject.toml && {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  host:
    - python >=3.7,<3.10
    - pip >=20.0.2
  run:
    - python >=3.7,<3.10
    - importlib-metadata  # [py==37]
    - numpy >=1.13
    - scipy >=1.0
    - numba >=0.50
    - h5py
    - requests
    - tqdm
    - pytz
    - pandas
    - inflection
    - requests
    - urllib3
    - quaternionic >=0.2
    - spherical
    - spinsfast  # [not win]

test:
  imports:
    - sxs

outputs:
  - name: sxs

  - name: sxs-ecosystem
    requirements:
      host:
        - python >=3.7,<3.10
      run:
        - python >=3.7,<3.10
        - ipywidgets
        - ipykernel
        - jupyter_contrib_nbextensions
        - jupyterlab
        - line_profiler
        - memory_profiler
        - matplotlib-base
        - sympy
        - corner
        - qgrid
        - rise
        - quaternion
        - spinsfast  # [not win]
        - spherical_functions  # [not win]
        - scri  # [not win]
        - {{ pin_subpackage('sxs', exact=True) }}
    test:
      imports:
        - sxs

about:
  home: https://github.com/sxs-collaboration/sxs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of python code used by the SXS collaboration
  description: |
    This package provides a number of utilities for use by the SXS collaboration, and others who use our data.
    For example, the `metadata` subpackage provides functions for reading and analyzing the metadata files
    provided with SXS simulations for describing the physics they represent.  Another important subpackage is
    `zenodo`, which provides handy functions for interacting with zenodo.org in general, and in particular our
    collection of simulation data on that site.
  dev_url: https://github.com/sxs-collaboration/sxs

extra:
  recipe-maintainers:
    - moble
