{% set name = "sxs" %}
{% set version = "2020.9.12" %}
{% set sha256 = "2757d2e70125213a4c3e7e495c47108c7d1ce1ae661ff69142d24ea9b3fcbed8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip >=20.0.2
  run:
    - python >=3.6
    - importlib-metadata
    - numpy >=1.13
    - scipy >=1.0
    - numba >=0.50
    - h5py
    - requests
    - tqdm
    - pytz
    - pandas
    - inflection
    - requests
    - urllib3
    - quaternionic >=0.2
    - spherical

test:
  imports:
    - sxs

outputs:
  - name: sxs

  - name: sxs-ecosystem
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - ipywidgets
        - ipykernel
        - jupyter_contrib_nbextensions
        - jupyterlab
        - line_profiler
        - memory_profiler
        - matplotlib
        - sympy
        - corner
        - qgrid
        - rise
        - quaternion
        - spinsfast
        - spherical_functions
        - scri
        - {{ pin_subpackage('sxs', exact=True) }}
    test:
      imports:
        - sxs

about:
  home: https://github.com/sxs-collaboration/sxs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of python code used by the SXS collaboration
  description: |
    This package provides a number of utilities for use by the SXS collaboration, and others who use our data.
    For example, the `metadata` subpackage provides functions for reading and analyzing the metadata files
    provided with SXS simulations for describing the physics they represent.  Another important subpackage is
    `zenodo`, which provides handy functions for interacting with zenodo.org in general, and in particular our
    collection of simulation data on that site.
  dev_url: https://github.com/sxs-collaboration/sxs

extra:
  recipe-maintainers:
    - moble
