{% set name = "sxs" %}
{% set version = "2020.3.21.10.12.32" %}
{% set sha256 = "531221b2360765a9f903468c7bb1cdca0b788ae090a9d51314eb4f3c825638dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: package_version={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - h5py
    - requests
    - requests-toolbelt
    - ads
    - lxml
    - feedparser
    - tqdm
    - pytz

test:
  imports:
    - sxs

about:
  home: https://github.com/moble/sxs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of python code used by the SXS collaboration
  description: |
    This package provides a number of utilities for use by the SXS collaboration, and others who use our data.
    For example, the `metadata` subpackage provides functions for reading and analyzing the metadata files
    provided with SXS simulations for describing the physics they represent.  Another important subpackage is
    `zenodo`, which provides handy functions for interacting with zenodo.org in general, and in particular our
    collection of simulation data on that site.
  dev_url: https://github.com/moble/sxs

extra:
  recipe-maintainers:
    - moble
