travis:
  secure:
    BINSTAR_TOKEN: pjCU1i2YTHViV9ik+PnuVZ4WKXdveneuuuIcX0WsU6I3pfLUFz/3d/eCvajje6i661eHf1F2Gbco4yHR2mrp5dY9+uP+X6TrErz94hDCDbJjtIv405i9tzDZJfyLnZAEiyLw10NcGNOF0q1ww4WFaOgB8ijDjn4mqS3yxI0oztCiSM9uPMpalJdxBp37HeZpJyhouApd8tPDlpExHsLfXUaRFfgh8DIj+sqmUJPyOaraasC9AG7Z9AcEnGANh+mZAHWIbwkJUnFmvxzxHthcVYIIV06z07Fvg+LR1npIqmC8oJcAcoyB2LI5t4Dn2qAWSZ5yFZ2xMbdS0vrULw6xCS/o6MICq7N0cNmZ4uHb4R33aeWBaLsSo1UwMoNFDWZaK4yftVNfzPi/y6fG1Y6Crreks5crd462gI0eJQ33miPuLt0p+2ZOBb29m26TdX8T5X/8136wwgKYNcZ+/YrXgSVgP3hyKza3tqpizQ+owAOCoA41dgyBadgd0uwKM9UnIP1yBudf9wneiLXW7m+l2Y4ygHYop7mR4EWmACa4LkUJWLXsd2KCp85PTfK1j5bkj1Y7JfykdjmZZJqcPxvUr//CCOwrbhep4/ktg08GBvLIT5wYXWQ16zEUc+3sRkgTeHMCjYFar5FbpX0Y5zHISx6BGsHsf3pwR6302VSfGh0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
